# Generated by Django 4.0.2 on 2022-02-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catergory',
            new_name='category',
        ),
    ]
